login: &login
  username: root
  password: "1234"
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: localhost
  socket: /var/run/mysqld/mysqld.sock

development:
  database: Debate_development
  <<: *login

test:
  database: Debate_test
  <<: *login

production:
  database: Debate_production
  <<: *login