login: &login
  username: root
  password:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: localhost
  socket: /var/run/mysqld/mysqld.sock

development:
  database: debate_development
  <<: *login

test:
  database: debate_test
  <<: *login

production:
  database: debate_production
  <<: *login